---
title: "Publications"
---

**Cohort profile: Health in Central Denmark (HICD) cohort - a register-based questionnaire survey on diabetes and related complications in the Central Denmark Region** <br>
Characteristics of the cohort is published in the cohort profile paper: <https://pubmed.ncbi.nlm.nih.gov/35798528/>


**Perception of Artificial Intelligence in Healthcare Among People with and Without Diabetes** <br>
A study examining Artificial Intelligence among individuals with and without diabetes has been published <https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4181697>


**Oral health in diabetes** <br>
A cross-sectional study with more than 40.000 participants found that a higher proportion of people with type 2 diabetes reported poor oral health compared to those without diabetes. Moreover, educational attainment modified the effect of diabetes on oral health, showing that the risk of reporting poor oral health increased with lower educational attainment <https://pubmed.ncbi.nlm.nih.gov/37500424/>


**Inequalities in healthcare utilisation among adults with type 2 diabetes** <br>
A new study sheds light on the healthcare attendance of adults with type 2 diabetes in the Central Denmark Region. The cross-sectional register-based study examined the prevalence of attending the ophthalmologist, podiatrist and dentist/dental hygienist among over 40.000 Danes with type 2 diabetes and found significant sociodemographic inequality in healthcare utilisation among people with type 2 diabetes, especially for dental attendance. The full article is available here <https://pubmed.ncbi.nlm.nih.gov/37890705/>
